# Generated by Django 5.2.1 on 2025-06-04 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_cartitem_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="cart_items",
                to="accounts.cart",
            ),
        ),
    ]
