# Generated by Django 5.2.1 on 2025-06-14 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_user_saved_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
